[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn realtime_server:app --host 0.0.0.0 --port $PORT --log-level info"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# Set these in Railway dashboard under Variables tab:
# OPENAI_API_KEY = "your-openai-api-key-here"
# BRAINWAVE_DATA_DIR = "/app/brainwave-data"

[experimental]
# Enable Railway's new build system
buildCommand = "pip install -r requirements.txt" 