[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn realtime_server:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# Set these in Railway dashboard:
# OPENAI_API_KEY = "your-openai-api-key"
# BRAINWAVE_DATA_DIR = "/app/data" 